velocity-mode: false
prevent-movement: true
prevent-damage: true
enable-mc-164316-fix: true
load-last: false
await-items-adder-host: true
use-new-force-pack-screen: true
try-to-stop-fake-accept-hacks: true
send-loading-title: true
delay-pack-sending-by: 0
web-server:
  enabled: false
  server-ip: localhost
  port: 8080
Server:
  packs:
    all:
      # The ResourcePack URL. This must be a direct URL, ending with .zip. For Dropbox URLs, add ?dl=1 to the end.
      # To host a local file on the embedded webserver, change this to the relative path of the force pack folder prefixed by "forcepack://".
      # For example, placing your resource pack as "plugins/ForcePack/pack.zip", the url will just be "forcepack://pack.zip".
      # ONLY PLAYERS ON 1.20.3+ CAN RECEIVE MULTIPLE RESOURCE PACKS. The first URL/Hash pair will be taken for older client versions.
      # URLs list and hashes list MUST BE THE SAME SIZE if generate-hash is disabled.
      urls: ["https://www.dropbox.com/scl/fi/cx6zdkto6679z5jkkg0y8/Eldin_Pack.zip?rlkey=x93r2novwfzqn4keiylszujst&st=f2fx24h7&dl=1"]
      # Whether to automatically generate the SHA-1 hash.
      # The hash setting will be ignored if this is true, however it will fall back to that if the generation fails.
      generate-hash: true
      # See https://fortitude.islandearth.net/forcepack/configuration#getting-the-sha-1-hash-of-a-resource-pack
      hashes: ["118AFFFC54CDCD308702F81BA24E03223F15FE5F"]
    # Here you can specify a pack format version-specific resource pack. You would copy the section above, replacing "all" with the number.
    # Note that the "all" section must be kept as a fallback.
    # See https://minecraft.wiki/w/Pack_format.

  Actions:
    # To disable commands, you can do Commands: []
    # List of valid actions: https://jd.advntr.dev/api/4.15.0/net/kyori/adventure/resource/ResourcePackStatus.html
    # DOWNLOADED, FAILED_RELOAD, DISCARDED only apply to 1.20.3+ clients.
    ACCEPTED:
      kick: false
      Commands: []
    DOWNLOADED:
      kick: false
      Commands: []
    SUCCESSFULLY_LOADED:
      kick: false
      Commands: []
    DECLINED:
      kick: true
      Commands: []
    FAILED_DOWNLOAD:
      kick: true
      Commands: []
    FAILED_RELOAD:
      kick: true
      Commands: []
    DISCARDED:
      kick: true
      Commands: []

  # Speed in ticks at which the ResourcePack prompt will be resent to the player (prevents escaping out)
  Update GUI Speed: 20
  Update GUI: true
  verify: true
  resend: true
  force-invalid-size: false
  geyser: false
  bypass-permission: false
  debug: false