method: SQL
sql:
  method: MYSQL
  host: ${DB_HOST}
  port: ${DB_PORT}
  database: Folia_SayanVanish
  username: ${DB_USER}
  password: ${DB_PASS}
  pool-properties:
    maximum-pool-size: 5
    minimum-idle: 5
    maximum-lifetime: 1800000
    keepalive-time: 0
    connection-timeout: 5000
    use-ssl: false
    verify-server-certificate: false
    allow-public-key-retrieval: true
  table-prefix: ""
redis:
  type: STANDALONE
  standalone:
    host: 127.0.0.1
    port: 6379
    user: ""
    password: ""
    ssl: false
use-cache-when-available: true
